# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aba1066ba822a07b7b15f221ba99e601e277002df2334c9907a40bae67d525b965860e70673070fe79ff40ff22eb6f56d888b779e948e75df57da84d43a8ef04

test:
  secret_key_base: 7e008730bd09f7c4fa727fec5bf543281cc8e608443eb05c3a90a64074a64200a55652e8a96d3b57fb5d895ca189018aaf339db280ea4827855c3992d54d450b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
